### PR TITLE
chore: remove bonus dependencies

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
I know I'm going to regret asking this, but what version of node:8 are we testing against @jkwlui @bcoe ?

**Comment by alexander-fenster** [comment]
Oh man. 

https://nodejs.org/api/assert.html#assert_assert_rejects_asyncfn_error_message

@JustinBeckwith `assert.rejects` was added in v10.0.0 :(  This PR is gonna wait for a little bit longer.

**Comment by JustinBeckwith** [comment]
Myles kindly backported it to 8.13 for us :)
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2018-11-20-version-8130-carbon-lts-mylesborins-prepared-by-bethgriggs

Can we just upgrade to run the latest build of 8 in our tests?

**Comment by alexander-fenster** [comment]
@jkwlui can we use the latest Node v8 in CI?

**Comment by alexander-fenster** [comment]
It looks like the feature is broken in Node v8.  Just compare this:

```
fenster-macbookpro:~ fenster$ node --version
v12.1.0
fenster-macbookpro:~ fenster$ node
Welcome to Node.js v12.1.0.
Type ".help" for more information.
> require('assert').rejects(Promise.reject(42))
Promise { <pending> }
> 
```

```
fenster-macbookpro:~ fenster$ node --version
v8.16.0
fenster-macbookpro:~ fenster$ node
> require('assert').rejects(Promise.reject(42))
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> (node:95195) UnhandledPromiseRejectionWarning: 42
(node:95195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95195) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "block" argument must be of type Function. Received type object
    at waitForActual (assert.js:723:11)
    at Function.rejects (assert.js:800:31)
    at repl:1:19
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
(node:95195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Pull request merged**
