### PR TITLE
feat: add api key support for ADC

### PR DESCRIPTION
**Pull request by arithmetic1728**
internal doc: go/gapic-api-key-support

This PR:
(1) adds `apiKey` property to `GoogleAuthOptions`
(2) if API key is provided via `apiKey` or `GOOGLE_API_KEY` env var, then `getApplicationDefaultAsync` will call `fromApiKey` to create a credential and return this credential. This credential will add a `x-goog-api-key` header with the API key value. We will still call `getProjectId` to find the project id, if not found return null

This PR has been tested with lanuage API sample: https://github.com/arithmetic1728/nodejs-api-key-sample

### CODE REVIEW

**Review by ralphstone1 — CHANGES_REQUESTED** [review]
Okay

**Comment by bcoe** [comment]
@arithmetic1728 just let me know when this is ready to come out of draft, if you need someone to look for Node.js readability.

**Comment by arithmetic1728** [comment]
@bcoe yes it is ready for review. Please add a `do not merge` for now, since I am still waiting for some server side CL which will be ready this week or next week. Thanks!

**Review by bcoe — CHANGES_REQUESTED** [review]
It would be worth adding a section to the README.md as well describing this new configuration option.

**Comment by SurferJeffAtGoogle** [comment]
I'm closing this PR due to inactivity.  @arithmetic1728 feel free to re-open and add the section to the README as requested in the review comments.

**Pull request closed without merging**
